version: '3.7'

volumes:
  orderer5.restaurant.com:
  couchdb4:
  couchdb5:
  peer0.restaurant.com:
  peer1.restaurant.com:

networks:
  blockchain_network:
    name: test_network

services:

  orderer5.restaurant.com:
    container_name: orderer5.restaurant.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_HOST=orderer5.restaurant.com
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=RestaurantMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls-msp/keystore/key.pem
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/restaurant/admin/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7061
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer5.restaurant.com:9449
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../../organizations/peerOrganizations/restaurant.com/orderers/orderer5.restaurant.com:/var/hyperledger/orderer/
      - ../../organizations/peerOrganizations/restaurant.com/admin:/var/hyperledger/restaurant/admin/
      - orderer5.restaurant.com:/var/hyperledger/production/orderer
    ports:
      - 7060:7050
      - 7061:7061
      - 9449:9449
    networks:
      - blockchain_network

  # couchdb가 먼저 실행 되어야한다.
  couchdb4:
    container_name: couchdb4
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "9984:5984"
    networks:
      - blockchain_network

  peer0.restaurant.com:
    container_name: peer0.restaurant.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test_network
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # Peer specific variables
      - CORE_PEER_ID=peer0.restaurant.com
      - CORE_PEER_ADDRESS=peer0.restaurant.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.restaurant.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      # bootstrap peer is the other peer in the same org
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.restaurant.com:17051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.restaurant.com:15051
      - CORE_PEER_LOCALMSPID=RestaurantMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.restaurant.com:9452
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0restaurant"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    depends_on:
      - couchdb4
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../organizations/peerOrganizations/restaurant.com/peers/peer0.restaurant.com:/etc/hyperledger/fabric
      - peer0.restaurant.com:/var/hyperledger/production
      - ../../configtx:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 15051:15051
      - 9452:9452
    networks:
      - blockchain_network

  # couchdb가 먼저 실행 되어야한다.
  couchdb5:
    container_name: couchdb5
    image: couchdb:3.3.2
    # image: hyperledger/fabric-couchdb:0.4.22
    # image: hyperledger/fabric-couchdb:x86_64-0.4.7
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      # - COUCHDB_USER=
      # - COUCHDB_PASSWORD=
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "10984:5984"
    networks:
      - blockchain_network

  peer1.restaurant.com:
    container_name: peer1.restaurant.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test_network
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls-msp/tlscacerts/tls-0-0-0-0-5054.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # Peer specific variables
      - CORE_PEER_ID=peer1.restaurant.com
      - CORE_PEER_ADDRESS=peer1.restaurant.com:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer1.restaurant.com:17052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:17052
      # bootstrap peer is the other peer in the same org
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.restaurant.com:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.restaurant.com:17051
      - CORE_PEER_LOCALMSPID=RestaurantMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.restaurant.com:9453
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1restaurant"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    depends_on:
      - couchdb5
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../organizations/peerOrganizations/restaurant.com/peers/peer1.restaurant.com:/etc/hyperledger/fabric
      - peer1.restaurant.com:/var/hyperledger/production
      - ../../configtx:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 17051:17051
      - 9453:9453
    networks:
      - blockchain_network
